module.exports = {
  development: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: "mysql",
    api_url: "http://localhost:3000",
    origin: "http://localhost:1234",
  },
  test: {
    username: "root",
    password: null,
    database: "database_test",
    host: "127.0.0.1",
    dialect: "mysql",
    api_url: "http://localhost:3000",
    origin: "http://localhost:1234",
  },
  production: {
    username: "root",
    password: null,
    database: "database_production",
    host: "127.0.0.1",
    dialect: "mysql",
    api_url: "https://my-json-server.typicode.com/queenkjuul/biblioteca",
    origin: "https://biblioteca-pf7p.onrender.com/",
  },
}
